export const requestsUrl = {
  registerApi: "/company/admin/registeration",
  loginApi: "/company/admin/login",
  profileUpdateApi: "/company",
  createTaskApi: "/company/tasks",
  getTasks: "company/tasks",
  updateprofilePic: "/company/photo",
  updateCompanyIcon: "/company/icon",
  coinPaymentApi: "/commerce/company/payment/coinpayment",
  cardPaymentApi: "/commerce/company/payment/stripe",
  offlinePayment: "/commerce/company/payment/offline",
  walletApi: "/commerce/company/wallet",
  configurePaypalPaymentApi: "/commerce/company/paypal/activate/plan",
  paypalPaymentApi: "/commerce/company/paypal/excecute/plan",
  paypalSecondPaymentApi: "/commerce/company/paypal/pay-now",
  updateTaskApi: "company/tasks",
  validatePackageApi: "/commerce/company/payment/validation",
  validatePaypalPackageApi: "/commerce/company/paypal/start/recurring",
  getInvoiceApi: "/commerce/company/invoices",
  updateAdmin: "/company/admin",
  getTaskSummaryById: "/company/report/summary",
  getReport: "/company/report/overview",
  resendVerifyEmail: "/company/admin/resend/validation/email",
  sendResetPasswordEmail: "/company/admin/reset/password",
  resetPassword: "/company/admin/change/password",
  selectCompany: "/company/admin/select/company",
  // createInteraction: "/admin/interactions",
  createInteraction: "/company/interactions",
  createCampaign: "/company/tasks/campaign",
  getCalendarData: "/company/tasks/calendar",
  inviteAdmin: "/company/invite/admin",
  getManagers: "/company/admin/all",
  assignManagers: "/company/assign/admin",
  getAllCalendarData: "company/tasks/calendar/all",
};
